=== DarKoul-Wmg/AMS-AWS-1/MP04 Lenguaje de Marcas/UF1_XML_HTML_CSS/Soluciones_PTs/Exemples DTD/school.dtd
<!ELEMENT root (students,teachers,rooms)>
<!ATTLIST root type CDATA #FIXED "database">
<!ELEMENT students (student*)>
<!ATTLIST students type CDATA #FIXED "table">
<!ELEMENT student (name, surname, age, course)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ATTLIST student type CDATA #FIXED "row">
<!ELEMENT teachers (teacher*)>
<!ATTLIST teachers type CDATA #FIXED "table">
<!ELEMENT teacher (name, surname, age, group)>
<!ATTLIST teacher type CDATA #FIXED "row"
                  tutor (yes|no) #REQUIRED>
<!ELEMENT group (#PCDATA)>
<!ELEMENT rooms (room*)>
<!ATTLIST rooms type CDATA #FIXED "table">
<!ELEMENT room (name, capacity)>
<!ATTLIST room type CDATA #FIXED "subtable">
<!ELEMENT capacity (#PCDATA)>

=== DarKoul-Wmg/AMS-AWS-1/MP04 Lenguaje de Marcas/UF1_XML_HTML_CSS/Soluciones_PTs/Exemples DTD/school.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "school.dtd">
<root type="database">
    <students type="table">
        <student>
            <name>Maria</name>
            <surname>Longstorm</surname>
            <age>18</age>
            <course>1B</course>
        </student>
        <student>
            <name>John</name>
            <surname>Bluefield</surname>
            <age>17</age>
            <course>1B</course>
        </student>
    </students>
    <teachers type="table">
        <teacher type="row" tutor="yes">
            <name>Emmie</name>
            <surname>Fastbelt</surname>
            <age>35</age>
            <group>1A</group>
        </teacher>
        <teacher type="row" tutor="yes">
            <name>Ernald</name>
            <surname>Softson</surname>
            <age>23</age>
            <group>1B</group>
        </teacher>
    </teachers>
    <rooms type="table">
        <room type="subtable">
            <name>Hall</name>
            <capacity>40</capacity>
        </room>
    </rooms>
</root>
