=== DarKoul-Wmg/AMS-AWS-1/MP04 Lenguaje de Marcas/UF1_XML_HTML_CSS/PR12_DTD_Molina_william/PR122.dtd
<!ELEMENT programacio (canal+)>
<!ELEMENT canal (publicitat, dia+)>
<!ATTLIST canal nom CDATA #REQUIRED>
<!ELEMENT publicitat (#PCDATA)>
<!ELEMENT dia (data, programes+)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT programes (programa*)>
<!ELEMENT programa (duracio, titol, resum*)>
<!ATTLIST programa edat CDATA #REQUIRED>
<!ATTLIST programa idioma CDATA #REQUIRED>
<!ELEMENT duracio (#PCDATA)>
<!ELEMENT titol (#PCDATA)>
<!ELEMENT resum (#PCDATA)>

=== DarKoul-Wmg/AMS-AWS-1/MP04 Lenguaje de Marcas/UF1_XML_HTML_CSS/PR12_DTD_Molina_william/PR122.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE programacio SYSTEM "PR122.dtd">
<programacio>
    <canal nom = "canal1">
        <publicitat></publicitat>

        <dia>
            <data></data>
            <programes>

                <programa edat = "18"
                idioma = "Esp, Ing">
                    <duracio></duracio>
                    <titol></titol>
                    <resum></resum>

                </programa>
            </programes>
        </dia>

    </canal>

    <canal nom = "canal2">

        <publicitat></publicitat>

        <dia>
            <data></data>
            <programes>

                <programa edat = "18"
                idioma = "Esp, Ing">
                    <duracio></duracio>
                    <titol></titol>
                    <resum></resum>
                    <resum></resum>

                </programa>
                <programa edat = "16"
                idioma = "Esp">
                    <duracio></duracio>
                    <titol></titol>
                    <resum></resum>


                </programa>
                <programa edat = "18"
                idioma = "Esp, Cat, Ing">
                    <duracio></duracio>
                    <titol></titol>
                    <resum></resum>
                    <resum></resum>
                    <resum></resum>

                </programa>
            </programes>
        </dia>

    </canal>
    <canal nom = "canal3">
   
        <publicitat></publicitat>
        <dia>
            <data></data>
            <programes>

                <programa edat = "18"
                idioma = "Esp, Cat">
                    <duracio></duracio>
                    <titol></titol>
                    <resum></resum>


                </programa>
                <programa edat = "14"
                idioma = "Esp, Ing">
                    <duracio></duracio>
                    <titol></titol>
                    <resum></resum>


                </programa>
            </programes>
        </dia>

    </canal>
    
</programacio>
