=== DarKoul-Wmg/AMS-AWS-1/MP04 Lenguaje de Marcas/UF1_XML_HTML_CSS/P01_WilliamMolina/003.dtd
<!ELEMENT datos (cd+)>
<!ATTLIST datos type CDATA #FIXED "database">
<!ELEMENT cd (nombre,grupo,lugar,productora,precio,fecha)>
<!ATTLIST cd id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT grupo (#PCDATA)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT productora (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>

=== DarKoul-Wmg/AMS-AWS-1/MP04 Lenguaje de Marcas/UF1_XML_HTML_CSS/P01_WilliamMolina/003.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE datos SYSTEM "003.dtd">
<!-- Exercici 3
    - Emplena l'arxiu 003.dtd que valida aquest XML
-->
<datos type="database">
    <cd id="id_0">
        <nombre>Empire Burlesque</nombre>
        <grupo>Bob Dylan</grupo>
        <lugar>USA</lugar>
        <productora>Columbia</productora>
        <precio>10.90</precio>
        <fecha>1985</fecha>
    </cd>
    <cd id="id_1">
        <nombre>Hide your heart</nombre>
        <grupo>Bonnie Tyler</grupo>
        <lugar>UK</lugar>
        <productora>CBS Records</productora>
        <precio>9.90</precio>
        <fecha>1988</fecha>
    </cd>
    <cd id="id_2">
        <nombre>Greatest Hits</nombre>
        <grupo>Dolly Parton</grupo>
        <lugar>USA</lugar>
        <productora>RCA</productora>
        <precio>9.90</precio>
        <fecha>1982</fecha>
    </cd>
    <cd id="id_3">
        <nombre>Still got the blues</nombre>
        <grupo>Gary Moore</grupo>
        <lugar>UK</lugar>
        <productora>Virgin records</productora>
        <precio>10.20</precio>
        <fecha>1990</fecha>
    </cd>
</datos>
