=== DarKoul-Wmg/AMS-AWS-1/MP04 Lenguaje de Marcas/UF1_XML_HTML_CSS/P01_WilliamMolina/004.dtd
<!ELEMENT usuarios (usuario*)>
<!ELEMENT usuario (nombre, direccion, cumple)>
<!ELEMENT nombre (apellido, segundoapellido, apodo)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT segundoapellido (#PCDATA)>
<!ELEMENT apodo (#PCDATA)>
<!ELEMENT direccion (correo, correoelectronico, movil, calle, numero)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT correoelectronico (#PCDATA)>
<!ELEMENT movil (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT cumple (año, mes, dia)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT dia (#PCDATA)>

=== DarKoul-Wmg/AMS-AWS-1/MP04 Lenguaje de Marcas/UF1_XML_HTML_CSS/P01_WilliamMolina/004.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE usuarios SYSTEM "004.dtd">
<!-- Exercici 4
    Genera l'arxiu XML que funciona segons
    la validació DTD adjunta, inventa't les dades
    i posa-hi almenys 1 persona
-->
<usuarios>
    <usuario>

        <nombre>
            <apellido>Molina</apellido>
            <segundoapellido>Galan</segundoapellido>
            <apodo>WallY</apodo>
        </nombre>

        <direccion>
            <correo>08940</correo>
            <correoelectronico>wally8@gmail.com</correoelectronico>
            <movil>666666666</movil>
            <calle>domenech i muntaner</calle>
            <numero>45</numero>
        </direccion>

        <cumple>
            <año>2002</año>
            <mes>abril</mes>
            <dia>9</dia>
        </cumple>

    </usuario>
    <usuario>

        <nombre>
            <apellido>Naharro</apellido>
            <segundoapellido>Rata</segundoapellido>
            <apodo>Caraslocas</apodo>
        </nombre>

        <direccion>
            <correo>08940</correo>
            <correoelectronico>pnaharro9@gmail.com</correoelectronico>
            <movil>666999666</movil>
            <calle>desmayo</calle>
            <numero>8</numero>
        </direccion>

        <cumple>
            <año>2002</año>
            <mes>octubre</mes>
            <dia>5</dia>
        </cumple>

    </usuario>
</usuarios>
